name: Generate ASCII Artwork
on: [push]

jobs:
    ascii_job:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: install cowsay program
              run: sudo apt-get install cowsay -y

            - name: list the repo files
              run: ls -ltra

            - name: Executing shell script
              run: ./ascii-script.sh
             
            